// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(rustylibFFI)
import rustylibFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_rustylib_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_rustylib_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate class UniffiHandleMap<T> {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt64: FfiConverterPrimitive {
    typealias FfiType = Int64
    typealias SwiftType = Int64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int64, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}


public struct HeartwoodCommit {
    public var oid: String
    public var message: String
    public var author: String
    public var timestamp: Int64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(oid: String, message: String, author: String, timestamp: Int64) {
        self.oid = oid
        self.message = message
        self.author = author
        self.timestamp = timestamp
    }
}



extension HeartwoodCommit: Equatable, Hashable {
    public static func ==(lhs: HeartwoodCommit, rhs: HeartwoodCommit) -> Bool {
        if lhs.oid != rhs.oid {
            return false
        }
        if lhs.message != rhs.message {
            return false
        }
        if lhs.author != rhs.author {
            return false
        }
        if lhs.timestamp != rhs.timestamp {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(oid)
        hasher.combine(message)
        hasher.combine(author)
        hasher.combine(timestamp)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHeartwoodCommit: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> HeartwoodCommit {
        return
            try HeartwoodCommit(
                oid: FfiConverterString.read(from: &buf), 
                message: FfiConverterString.read(from: &buf), 
                author: FfiConverterString.read(from: &buf), 
                timestamp: FfiConverterInt64.read(from: &buf)
        )
    }

    public static func write(_ value: HeartwoodCommit, into buf: inout [UInt8]) {
        FfiConverterString.write(value.oid, into: &buf)
        FfiConverterString.write(value.message, into: &buf)
        FfiConverterString.write(value.author, into: &buf)
        FfiConverterInt64.write(value.timestamp, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHeartwoodCommit_lift(_ buf: RustBuffer) throws -> HeartwoodCommit {
    return try FfiConverterTypeHeartwoodCommit.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHeartwoodCommit_lower(_ value: HeartwoodCommit) -> RustBuffer {
    return FfiConverterTypeHeartwoodCommit.lower(value)
}


public struct HeartwoodFollowPolicy {
    public var nid: String
    public var alias: String?
    public var policy: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(nid: String, alias: String?, policy: String) {
        self.nid = nid
        self.alias = alias
        self.policy = policy
    }
}



extension HeartwoodFollowPolicy: Equatable, Hashable {
    public static func ==(lhs: HeartwoodFollowPolicy, rhs: HeartwoodFollowPolicy) -> Bool {
        if lhs.nid != rhs.nid {
            return false
        }
        if lhs.alias != rhs.alias {
            return false
        }
        if lhs.policy != rhs.policy {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(nid)
        hasher.combine(alias)
        hasher.combine(policy)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHeartwoodFollowPolicy: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> HeartwoodFollowPolicy {
        return
            try HeartwoodFollowPolicy(
                nid: FfiConverterString.read(from: &buf), 
                alias: FfiConverterOptionString.read(from: &buf), 
                policy: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: HeartwoodFollowPolicy, into buf: inout [UInt8]) {
        FfiConverterString.write(value.nid, into: &buf)
        FfiConverterOptionString.write(value.alias, into: &buf)
        FfiConverterString.write(value.policy, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHeartwoodFollowPolicy_lift(_ buf: RustBuffer) throws -> HeartwoodFollowPolicy {
    return try FfiConverterTypeHeartwoodFollowPolicy.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHeartwoodFollowPolicy_lower(_ value: HeartwoodFollowPolicy) -> RustBuffer {
    return FfiConverterTypeHeartwoodFollowPolicy.lower(value)
}


public struct HeartwoodIssueCounts {
    public var `open`: UInt64
    public var closed: UInt64
    public var total: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(`open`: UInt64, closed: UInt64, total: UInt64) {
        self.`open` = `open`
        self.closed = closed
        self.total = total
    }
}



extension HeartwoodIssueCounts: Equatable, Hashable {
    public static func ==(lhs: HeartwoodIssueCounts, rhs: HeartwoodIssueCounts) -> Bool {
        if lhs.`open` != rhs.`open` {
            return false
        }
        if lhs.closed != rhs.closed {
            return false
        }
        if lhs.total != rhs.total {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(`open`)
        hasher.combine(closed)
        hasher.combine(total)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHeartwoodIssueCounts: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> HeartwoodIssueCounts {
        return
            try HeartwoodIssueCounts(
                open: FfiConverterUInt64.read(from: &buf), 
                closed: FfiConverterUInt64.read(from: &buf), 
                total: FfiConverterUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: HeartwoodIssueCounts, into buf: inout [UInt8]) {
        FfiConverterUInt64.write(value.`open`, into: &buf)
        FfiConverterUInt64.write(value.closed, into: &buf)
        FfiConverterUInt64.write(value.total, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHeartwoodIssueCounts_lift(_ buf: RustBuffer) throws -> HeartwoodIssueCounts {
    return try FfiConverterTypeHeartwoodIssueCounts.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHeartwoodIssueCounts_lower(_ value: HeartwoodIssueCounts) -> RustBuffer {
    return FfiConverterTypeHeartwoodIssueCounts.lower(value)
}


public struct HeartwoodNodeInfo {
    public var alias: String
    public var nodeId: String
    public var userAgent: String
    public var network: String
    public var relay: String
    public var listenAddresses: [String]
    public var externalAddresses: [String]
    public var connectAddresses: [String]
    public var paths: HeartwoodPaths

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(alias: String, nodeId: String, userAgent: String, network: String, relay: String, listenAddresses: [String], externalAddresses: [String], connectAddresses: [String], paths: HeartwoodPaths) {
        self.alias = alias
        self.nodeId = nodeId
        self.userAgent = userAgent
        self.network = network
        self.relay = relay
        self.listenAddresses = listenAddresses
        self.externalAddresses = externalAddresses
        self.connectAddresses = connectAddresses
        self.paths = paths
    }
}



extension HeartwoodNodeInfo: Equatable, Hashable {
    public static func ==(lhs: HeartwoodNodeInfo, rhs: HeartwoodNodeInfo) -> Bool {
        if lhs.alias != rhs.alias {
            return false
        }
        if lhs.nodeId != rhs.nodeId {
            return false
        }
        if lhs.userAgent != rhs.userAgent {
            return false
        }
        if lhs.network != rhs.network {
            return false
        }
        if lhs.relay != rhs.relay {
            return false
        }
        if lhs.listenAddresses != rhs.listenAddresses {
            return false
        }
        if lhs.externalAddresses != rhs.externalAddresses {
            return false
        }
        if lhs.connectAddresses != rhs.connectAddresses {
            return false
        }
        if lhs.paths != rhs.paths {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(alias)
        hasher.combine(nodeId)
        hasher.combine(userAgent)
        hasher.combine(network)
        hasher.combine(relay)
        hasher.combine(listenAddresses)
        hasher.combine(externalAddresses)
        hasher.combine(connectAddresses)
        hasher.combine(paths)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHeartwoodNodeInfo: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> HeartwoodNodeInfo {
        return
            try HeartwoodNodeInfo(
                alias: FfiConverterString.read(from: &buf), 
                nodeId: FfiConverterString.read(from: &buf), 
                userAgent: FfiConverterString.read(from: &buf), 
                network: FfiConverterString.read(from: &buf), 
                relay: FfiConverterString.read(from: &buf), 
                listenAddresses: FfiConverterSequenceString.read(from: &buf), 
                externalAddresses: FfiConverterSequenceString.read(from: &buf), 
                connectAddresses: FfiConverterSequenceString.read(from: &buf), 
                paths: FfiConverterTypeHeartwoodPaths.read(from: &buf)
        )
    }

    public static func write(_ value: HeartwoodNodeInfo, into buf: inout [UInt8]) {
        FfiConverterString.write(value.alias, into: &buf)
        FfiConverterString.write(value.nodeId, into: &buf)
        FfiConverterString.write(value.userAgent, into: &buf)
        FfiConverterString.write(value.network, into: &buf)
        FfiConverterString.write(value.relay, into: &buf)
        FfiConverterSequenceString.write(value.listenAddresses, into: &buf)
        FfiConverterSequenceString.write(value.externalAddresses, into: &buf)
        FfiConverterSequenceString.write(value.connectAddresses, into: &buf)
        FfiConverterTypeHeartwoodPaths.write(value.paths, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHeartwoodNodeInfo_lift(_ buf: RustBuffer) throws -> HeartwoodNodeInfo {
    return try FfiConverterTypeHeartwoodNodeInfo.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHeartwoodNodeInfo_lower(_ value: HeartwoodNodeInfo) -> RustBuffer {
    return FfiConverterTypeHeartwoodNodeInfo.lower(value)
}


public struct HeartwoodNodeStatus {
    public var running: Bool
    public var socket: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(running: Bool, socket: String) {
        self.running = running
        self.socket = socket
    }
}



extension HeartwoodNodeStatus: Equatable, Hashable {
    public static func ==(lhs: HeartwoodNodeStatus, rhs: HeartwoodNodeStatus) -> Bool {
        if lhs.running != rhs.running {
            return false
        }
        if lhs.socket != rhs.socket {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(running)
        hasher.combine(socket)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHeartwoodNodeStatus: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> HeartwoodNodeStatus {
        return
            try HeartwoodNodeStatus(
                running: FfiConverterBool.read(from: &buf), 
                socket: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: HeartwoodNodeStatus, into buf: inout [UInt8]) {
        FfiConverterBool.write(value.running, into: &buf)
        FfiConverterString.write(value.socket, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHeartwoodNodeStatus_lift(_ buf: RustBuffer) throws -> HeartwoodNodeStatus {
    return try FfiConverterTypeHeartwoodNodeStatus.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHeartwoodNodeStatus_lower(_ value: HeartwoodNodeStatus) -> RustBuffer {
    return FfiConverterTypeHeartwoodNodeStatus.lower(value)
}


public struct HeartwoodNotificationCount {
    public var rid: String
    public var count: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(rid: String, count: UInt64) {
        self.rid = rid
        self.count = count
    }
}



extension HeartwoodNotificationCount: Equatable, Hashable {
    public static func ==(lhs: HeartwoodNotificationCount, rhs: HeartwoodNotificationCount) -> Bool {
        if lhs.rid != rhs.rid {
            return false
        }
        if lhs.count != rhs.count {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(rid)
        hasher.combine(count)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHeartwoodNotificationCount: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> HeartwoodNotificationCount {
        return
            try HeartwoodNotificationCount(
                rid: FfiConverterString.read(from: &buf), 
                count: FfiConverterUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: HeartwoodNotificationCount, into buf: inout [UInt8]) {
        FfiConverterString.write(value.rid, into: &buf)
        FfiConverterUInt64.write(value.count, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHeartwoodNotificationCount_lift(_ buf: RustBuffer) throws -> HeartwoodNotificationCount {
    return try FfiConverterTypeHeartwoodNotificationCount.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHeartwoodNotificationCount_lower(_ value: HeartwoodNotificationCount) -> RustBuffer {
    return FfiConverterTypeHeartwoodNotificationCount.lower(value)
}


public struct HeartwoodPatchCounts {
    public var `open`: UInt64
    public var draft: UInt64
    public var archived: UInt64
    public var merged: UInt64
    public var total: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(`open`: UInt64, draft: UInt64, archived: UInt64, merged: UInt64, total: UInt64) {
        self.`open` = `open`
        self.draft = draft
        self.archived = archived
        self.merged = merged
        self.total = total
    }
}



extension HeartwoodPatchCounts: Equatable, Hashable {
    public static func ==(lhs: HeartwoodPatchCounts, rhs: HeartwoodPatchCounts) -> Bool {
        if lhs.`open` != rhs.`open` {
            return false
        }
        if lhs.draft != rhs.draft {
            return false
        }
        if lhs.archived != rhs.archived {
            return false
        }
        if lhs.merged != rhs.merged {
            return false
        }
        if lhs.total != rhs.total {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(`open`)
        hasher.combine(draft)
        hasher.combine(archived)
        hasher.combine(merged)
        hasher.combine(total)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHeartwoodPatchCounts: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> HeartwoodPatchCounts {
        return
            try HeartwoodPatchCounts(
                open: FfiConverterUInt64.read(from: &buf), 
                draft: FfiConverterUInt64.read(from: &buf), 
                archived: FfiConverterUInt64.read(from: &buf), 
                merged: FfiConverterUInt64.read(from: &buf), 
                total: FfiConverterUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: HeartwoodPatchCounts, into buf: inout [UInt8]) {
        FfiConverterUInt64.write(value.`open`, into: &buf)
        FfiConverterUInt64.write(value.draft, into: &buf)
        FfiConverterUInt64.write(value.archived, into: &buf)
        FfiConverterUInt64.write(value.merged, into: &buf)
        FfiConverterUInt64.write(value.total, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHeartwoodPatchCounts_lift(_ buf: RustBuffer) throws -> HeartwoodPatchCounts {
    return try FfiConverterTypeHeartwoodPatchCounts.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHeartwoodPatchCounts_lower(_ value: HeartwoodPatchCounts) -> RustBuffer {
    return FfiConverterTypeHeartwoodPatchCounts.lower(value)
}


public struct HeartwoodPaths {
    public var home: String
    public var storage: String
    public var config: String
    public var keys: String
    public var node: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(home: String, storage: String, config: String, keys: String, node: String) {
        self.home = home
        self.storage = storage
        self.config = config
        self.keys = keys
        self.node = node
    }
}



extension HeartwoodPaths: Equatable, Hashable {
    public static func ==(lhs: HeartwoodPaths, rhs: HeartwoodPaths) -> Bool {
        if lhs.home != rhs.home {
            return false
        }
        if lhs.storage != rhs.storage {
            return false
        }
        if lhs.config != rhs.config {
            return false
        }
        if lhs.keys != rhs.keys {
            return false
        }
        if lhs.node != rhs.node {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(home)
        hasher.combine(storage)
        hasher.combine(config)
        hasher.combine(keys)
        hasher.combine(node)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHeartwoodPaths: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> HeartwoodPaths {
        return
            try HeartwoodPaths(
                home: FfiConverterString.read(from: &buf), 
                storage: FfiConverterString.read(from: &buf), 
                config: FfiConverterString.read(from: &buf), 
                keys: FfiConverterString.read(from: &buf), 
                node: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: HeartwoodPaths, into buf: inout [UInt8]) {
        FfiConverterString.write(value.home, into: &buf)
        FfiConverterString.write(value.storage, into: &buf)
        FfiConverterString.write(value.config, into: &buf)
        FfiConverterString.write(value.keys, into: &buf)
        FfiConverterString.write(value.node, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHeartwoodPaths_lift(_ buf: RustBuffer) throws -> HeartwoodPaths {
    return try FfiConverterTypeHeartwoodPaths.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHeartwoodPaths_lower(_ value: HeartwoodPaths) -> RustBuffer {
    return FfiConverterTypeHeartwoodPaths.lower(value)
}


public struct HeartwoodProjectInfo {
    public var name: String
    public var description: String
    public var defaultBranch: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(name: String, description: String, defaultBranch: String) {
        self.name = name
        self.description = description
        self.defaultBranch = defaultBranch
    }
}



extension HeartwoodProjectInfo: Equatable, Hashable {
    public static func ==(lhs: HeartwoodProjectInfo, rhs: HeartwoodProjectInfo) -> Bool {
        if lhs.name != rhs.name {
            return false
        }
        if lhs.description != rhs.description {
            return false
        }
        if lhs.defaultBranch != rhs.defaultBranch {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(name)
        hasher.combine(description)
        hasher.combine(defaultBranch)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHeartwoodProjectInfo: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> HeartwoodProjectInfo {
        return
            try HeartwoodProjectInfo(
                name: FfiConverterString.read(from: &buf), 
                description: FfiConverterString.read(from: &buf), 
                defaultBranch: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: HeartwoodProjectInfo, into buf: inout [UInt8]) {
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterString.write(value.description, into: &buf)
        FfiConverterString.write(value.defaultBranch, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHeartwoodProjectInfo_lift(_ buf: RustBuffer) throws -> HeartwoodProjectInfo {
    return try FfiConverterTypeHeartwoodProjectInfo.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHeartwoodProjectInfo_lower(_ value: HeartwoodProjectInfo) -> RustBuffer {
    return FfiConverterTypeHeartwoodProjectInfo.lower(value)
}


public struct HeartwoodRef {
    public var name: String
    public var oid: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(name: String, oid: String) {
        self.name = name
        self.oid = oid
    }
}



extension HeartwoodRef: Equatable, Hashable {
    public static func ==(lhs: HeartwoodRef, rhs: HeartwoodRef) -> Bool {
        if lhs.name != rhs.name {
            return false
        }
        if lhs.oid != rhs.oid {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(name)
        hasher.combine(oid)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHeartwoodRef: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> HeartwoodRef {
        return
            try HeartwoodRef(
                name: FfiConverterString.read(from: &buf), 
                oid: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: HeartwoodRef, into buf: inout [UInt8]) {
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterString.write(value.oid, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHeartwoodRef_lift(_ buf: RustBuffer) throws -> HeartwoodRef {
    return try FfiConverterTypeHeartwoodRef.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHeartwoodRef_lower(_ value: HeartwoodRef) -> RustBuffer {
    return FfiConverterTypeHeartwoodRef.lower(value)
}


public struct HeartwoodRemote {
    public var nid: String
    public var refs: [HeartwoodRef]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(nid: String, refs: [HeartwoodRef]) {
        self.nid = nid
        self.refs = refs
    }
}



extension HeartwoodRemote: Equatable, Hashable {
    public static func ==(lhs: HeartwoodRemote, rhs: HeartwoodRemote) -> Bool {
        if lhs.nid != rhs.nid {
            return false
        }
        if lhs.refs != rhs.refs {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(nid)
        hasher.combine(refs)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHeartwoodRemote: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> HeartwoodRemote {
        return
            try HeartwoodRemote(
                nid: FfiConverterString.read(from: &buf), 
                refs: FfiConverterSequenceTypeHeartwoodRef.read(from: &buf)
        )
    }

    public static func write(_ value: HeartwoodRemote, into buf: inout [UInt8]) {
        FfiConverterString.write(value.nid, into: &buf)
        FfiConverterSequenceTypeHeartwoodRef.write(value.refs, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHeartwoodRemote_lift(_ buf: RustBuffer) throws -> HeartwoodRemote {
    return try FfiConverterTypeHeartwoodRemote.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHeartwoodRemote_lower(_ value: HeartwoodRemote) -> RustBuffer {
    return FfiConverterTypeHeartwoodRemote.lower(value)
}


public struct HeartwoodRepositoryInfo {
    public var rid: String
    public var head: String?
    public var project: HeartwoodProjectInfo?
    public var delegates: [String]
    public var threshold: UInt32
    public var visibility: String
    public var refsState: String
    public var syncedAt: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(rid: String, head: String?, project: HeartwoodProjectInfo?, delegates: [String], threshold: UInt32, visibility: String, refsState: String, syncedAt: String?) {
        self.rid = rid
        self.head = head
        self.project = project
        self.delegates = delegates
        self.threshold = threshold
        self.visibility = visibility
        self.refsState = refsState
        self.syncedAt = syncedAt
    }
}



extension HeartwoodRepositoryInfo: Equatable, Hashable {
    public static func ==(lhs: HeartwoodRepositoryInfo, rhs: HeartwoodRepositoryInfo) -> Bool {
        if lhs.rid != rhs.rid {
            return false
        }
        if lhs.head != rhs.head {
            return false
        }
        if lhs.project != rhs.project {
            return false
        }
        if lhs.delegates != rhs.delegates {
            return false
        }
        if lhs.threshold != rhs.threshold {
            return false
        }
        if lhs.visibility != rhs.visibility {
            return false
        }
        if lhs.refsState != rhs.refsState {
            return false
        }
        if lhs.syncedAt != rhs.syncedAt {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(rid)
        hasher.combine(head)
        hasher.combine(project)
        hasher.combine(delegates)
        hasher.combine(threshold)
        hasher.combine(visibility)
        hasher.combine(refsState)
        hasher.combine(syncedAt)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHeartwoodRepositoryInfo: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> HeartwoodRepositoryInfo {
        return
            try HeartwoodRepositoryInfo(
                rid: FfiConverterString.read(from: &buf), 
                head: FfiConverterOptionString.read(from: &buf), 
                project: FfiConverterOptionTypeHeartwoodProjectInfo.read(from: &buf), 
                delegates: FfiConverterSequenceString.read(from: &buf), 
                threshold: FfiConverterUInt32.read(from: &buf), 
                visibility: FfiConverterString.read(from: &buf), 
                refsState: FfiConverterString.read(from: &buf), 
                syncedAt: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: HeartwoodRepositoryInfo, into buf: inout [UInt8]) {
        FfiConverterString.write(value.rid, into: &buf)
        FfiConverterOptionString.write(value.head, into: &buf)
        FfiConverterOptionTypeHeartwoodProjectInfo.write(value.project, into: &buf)
        FfiConverterSequenceString.write(value.delegates, into: &buf)
        FfiConverterUInt32.write(value.threshold, into: &buf)
        FfiConverterString.write(value.visibility, into: &buf)
        FfiConverterString.write(value.refsState, into: &buf)
        FfiConverterOptionString.write(value.syncedAt, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHeartwoodRepositoryInfo_lift(_ buf: RustBuffer) throws -> HeartwoodRepositoryInfo {
    return try FfiConverterTypeHeartwoodRepositoryInfo.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHeartwoodRepositoryInfo_lower(_ value: HeartwoodRepositoryInfo) -> RustBuffer {
    return FfiConverterTypeHeartwoodRepositoryInfo.lower(value)
}


public struct HeartwoodRoutingSummary {
    public var entries: UInt64
    public var seededRepos: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(entries: UInt64, seededRepos: UInt64) {
        self.entries = entries
        self.seededRepos = seededRepos
    }
}



extension HeartwoodRoutingSummary: Equatable, Hashable {
    public static func ==(lhs: HeartwoodRoutingSummary, rhs: HeartwoodRoutingSummary) -> Bool {
        if lhs.entries != rhs.entries {
            return false
        }
        if lhs.seededRepos != rhs.seededRepos {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(entries)
        hasher.combine(seededRepos)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHeartwoodRoutingSummary: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> HeartwoodRoutingSummary {
        return
            try HeartwoodRoutingSummary(
                entries: FfiConverterUInt64.read(from: &buf), 
                seededRepos: FfiConverterUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: HeartwoodRoutingSummary, into buf: inout [UInt8]) {
        FfiConverterUInt64.write(value.entries, into: &buf)
        FfiConverterUInt64.write(value.seededRepos, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHeartwoodRoutingSummary_lift(_ buf: RustBuffer) throws -> HeartwoodRoutingSummary {
    return try FfiConverterTypeHeartwoodRoutingSummary.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHeartwoodRoutingSummary_lower(_ value: HeartwoodRoutingSummary) -> RustBuffer {
    return FfiConverterTypeHeartwoodRoutingSummary.lower(value)
}


public struct HeartwoodSeedPolicy {
    public var rid: String
    public var policy: String
    public var scope: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(rid: String, policy: String, scope: String?) {
        self.rid = rid
        self.policy = policy
        self.scope = scope
    }
}



extension HeartwoodSeedPolicy: Equatable, Hashable {
    public static func ==(lhs: HeartwoodSeedPolicy, rhs: HeartwoodSeedPolicy) -> Bool {
        if lhs.rid != rhs.rid {
            return false
        }
        if lhs.policy != rhs.policy {
            return false
        }
        if lhs.scope != rhs.scope {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(rid)
        hasher.combine(policy)
        hasher.combine(scope)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHeartwoodSeedPolicy: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> HeartwoodSeedPolicy {
        return
            try HeartwoodSeedPolicy(
                rid: FfiConverterString.read(from: &buf), 
                policy: FfiConverterString.read(from: &buf), 
                scope: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: HeartwoodSeedPolicy, into buf: inout [UInt8]) {
        FfiConverterString.write(value.rid, into: &buf)
        FfiConverterString.write(value.policy, into: &buf)
        FfiConverterOptionString.write(value.scope, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHeartwoodSeedPolicy_lift(_ buf: RustBuffer) throws -> HeartwoodSeedPolicy {
    return try FfiConverterTypeHeartwoodSeedPolicy.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHeartwoodSeedPolicy_lower(_ value: HeartwoodSeedPolicy) -> RustBuffer {
    return FfiConverterTypeHeartwoodSeedPolicy.lower(value)
}


public struct HeartwoodSession {
    public var nid: String
    public var link: String
    public var addr: String
    public var state: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(nid: String, link: String, addr: String, state: String) {
        self.nid = nid
        self.link = link
        self.addr = addr
        self.state = state
    }
}



extension HeartwoodSession: Equatable, Hashable {
    public static func ==(lhs: HeartwoodSession, rhs: HeartwoodSession) -> Bool {
        if lhs.nid != rhs.nid {
            return false
        }
        if lhs.link != rhs.link {
            return false
        }
        if lhs.addr != rhs.addr {
            return false
        }
        if lhs.state != rhs.state {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(nid)
        hasher.combine(link)
        hasher.combine(addr)
        hasher.combine(state)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHeartwoodSession: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> HeartwoodSession {
        return
            try HeartwoodSession(
                nid: FfiConverterString.read(from: &buf), 
                link: FfiConverterString.read(from: &buf), 
                addr: FfiConverterString.read(from: &buf), 
                state: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: HeartwoodSession, into buf: inout [UInt8]) {
        FfiConverterString.write(value.nid, into: &buf)
        FfiConverterString.write(value.link, into: &buf)
        FfiConverterString.write(value.addr, into: &buf)
        FfiConverterString.write(value.state, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHeartwoodSession_lift(_ buf: RustBuffer) throws -> HeartwoodSession {
    return try FfiConverterTypeHeartwoodSession.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHeartwoodSession_lower(_ value: HeartwoodSession) -> RustBuffer {
    return FfiConverterTypeHeartwoodSession.lower(value)
}


public enum HeartwoodError {

    
    
    case Profile(String
    )
    case Storage(String
    )
    case InvalidRepoId(String
    )
    case InvalidAlias(String
    )
    case InvalidRelay(String
    )
    case InvalidNetwork(String
    )
    case ConfigWrite(String
    )
    case InvalidAddress(String
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHeartwoodError: FfiConverterRustBuffer {
    typealias SwiftType = HeartwoodError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> HeartwoodError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Profile(
            try FfiConverterString.read(from: &buf)
            )
        case 2: return .Storage(
            try FfiConverterString.read(from: &buf)
            )
        case 3: return .InvalidRepoId(
            try FfiConverterString.read(from: &buf)
            )
        case 4: return .InvalidAlias(
            try FfiConverterString.read(from: &buf)
            )
        case 5: return .InvalidRelay(
            try FfiConverterString.read(from: &buf)
            )
        case 6: return .InvalidNetwork(
            try FfiConverterString.read(from: &buf)
            )
        case 7: return .ConfigWrite(
            try FfiConverterString.read(from: &buf)
            )
        case 8: return .InvalidAddress(
            try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: HeartwoodError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .Profile(v1):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .Storage(v1):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .InvalidRepoId(v1):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .InvalidAlias(v1):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .InvalidRelay(v1):
            writeInt(&buf, Int32(5))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .InvalidNetwork(v1):
            writeInt(&buf, Int32(6))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .ConfigWrite(v1):
            writeInt(&buf, Int32(7))
            FfiConverterString.write(v1, into: &buf)
            
        
        case let .InvalidAddress(v1):
            writeInt(&buf, Int32(8))
            FfiConverterString.write(v1, into: &buf)
            
        }
    }
}


extension HeartwoodError: Equatable, Hashable {}

extension HeartwoodError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeHeartwoodIssueCounts: FfiConverterRustBuffer {
    typealias SwiftType = HeartwoodIssueCounts?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeHeartwoodIssueCounts.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeHeartwoodIssueCounts.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeHeartwoodPatchCounts: FfiConverterRustBuffer {
    typealias SwiftType = HeartwoodPatchCounts?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeHeartwoodPatchCounts.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeHeartwoodPatchCounts.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeHeartwoodProjectInfo: FfiConverterRustBuffer {
    typealias SwiftType = HeartwoodProjectInfo?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeHeartwoodProjectInfo.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeHeartwoodProjectInfo.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeHeartwoodRepositoryInfo: FfiConverterRustBuffer {
    typealias SwiftType = HeartwoodRepositoryInfo?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeHeartwoodRepositoryInfo.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeHeartwoodRepositoryInfo.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeHeartwoodCommit: FfiConverterRustBuffer {
    typealias SwiftType = [HeartwoodCommit]

    public static func write(_ value: [HeartwoodCommit], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeHeartwoodCommit.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [HeartwoodCommit] {
        let len: Int32 = try readInt(&buf)
        var seq = [HeartwoodCommit]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeHeartwoodCommit.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeHeartwoodFollowPolicy: FfiConverterRustBuffer {
    typealias SwiftType = [HeartwoodFollowPolicy]

    public static func write(_ value: [HeartwoodFollowPolicy], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeHeartwoodFollowPolicy.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [HeartwoodFollowPolicy] {
        let len: Int32 = try readInt(&buf)
        var seq = [HeartwoodFollowPolicy]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeHeartwoodFollowPolicy.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeHeartwoodNotificationCount: FfiConverterRustBuffer {
    typealias SwiftType = [HeartwoodNotificationCount]

    public static func write(_ value: [HeartwoodNotificationCount], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeHeartwoodNotificationCount.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [HeartwoodNotificationCount] {
        let len: Int32 = try readInt(&buf)
        var seq = [HeartwoodNotificationCount]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeHeartwoodNotificationCount.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeHeartwoodRef: FfiConverterRustBuffer {
    typealias SwiftType = [HeartwoodRef]

    public static func write(_ value: [HeartwoodRef], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeHeartwoodRef.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [HeartwoodRef] {
        let len: Int32 = try readInt(&buf)
        var seq = [HeartwoodRef]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeHeartwoodRef.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeHeartwoodRemote: FfiConverterRustBuffer {
    typealias SwiftType = [HeartwoodRemote]

    public static func write(_ value: [HeartwoodRemote], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeHeartwoodRemote.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [HeartwoodRemote] {
        let len: Int32 = try readInt(&buf)
        var seq = [HeartwoodRemote]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeHeartwoodRemote.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeHeartwoodRepositoryInfo: FfiConverterRustBuffer {
    typealias SwiftType = [HeartwoodRepositoryInfo]

    public static func write(_ value: [HeartwoodRepositoryInfo], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeHeartwoodRepositoryInfo.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [HeartwoodRepositoryInfo] {
        let len: Int32 = try readInt(&buf)
        var seq = [HeartwoodRepositoryInfo]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeHeartwoodRepositoryInfo.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeHeartwoodSeedPolicy: FfiConverterRustBuffer {
    typealias SwiftType = [HeartwoodSeedPolicy]

    public static func write(_ value: [HeartwoodSeedPolicy], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeHeartwoodSeedPolicy.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [HeartwoodSeedPolicy] {
        let len: Int32 = try readInt(&buf)
        var seq = [HeartwoodSeedPolicy]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeHeartwoodSeedPolicy.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeHeartwoodSession: FfiConverterRustBuffer {
    typealias SwiftType = [HeartwoodSession]

    public static func write(_ value: [HeartwoodSession], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeHeartwoodSession.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [HeartwoodSession] {
        let len: Int32 = try readInt(&buf)
        var seq = [HeartwoodSession]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeHeartwoodSession.read(from: &buf))
        }
        return seq
    }
}
public func heartwoodAddConnectAddress(address: String)throws  {try rustCallWithError(FfiConverterTypeHeartwoodError.lift) {
    uniffi_rustylib_fn_func_heartwood_add_connect_address(
        FfiConverterString.lower(address),$0
    )
}
}
public func heartwoodAddExternalAddress(address: String)throws  {try rustCallWithError(FfiConverterTypeHeartwoodError.lift) {
    uniffi_rustylib_fn_func_heartwood_add_external_address(
        FfiConverterString.lower(address),$0
    )
}
}
public func heartwoodAddListenAddress(address: String)throws  {try rustCallWithError(FfiConverterTypeHeartwoodError.lift) {
    uniffi_rustylib_fn_func_heartwood_add_listen_address(
        FfiConverterString.lower(address),$0
    )
}
}
public func heartwoodAliasForNode(nid: String)throws  -> String? {
    return try  FfiConverterOptionString.lift(try rustCallWithError(FfiConverterTypeHeartwoodError.lift) {
    uniffi_rustylib_fn_func_heartwood_alias_for_node(
        FfiConverterString.lower(nid),$0
    )
})
}
public func heartwoodAnswer() -> UInt32 {
    return try!  FfiConverterUInt32.lift(try! rustCall() {
    uniffi_rustylib_fn_func_heartwood_answer($0
    )
})
}
public func heartwoodCommit() -> String {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_rustylib_fn_func_heartwood_commit($0
    )
})
}
public func heartwoodFollowPolicies()throws  -> [HeartwoodFollowPolicy] {
    return try  FfiConverterSequenceTypeHeartwoodFollowPolicy.lift(try rustCallWithError(FfiConverterTypeHeartwoodError.lift) {
    uniffi_rustylib_fn_func_heartwood_follow_policies($0
    )
})
}
public func heartwoodHasProfile() -> Bool {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_rustylib_fn_func_heartwood_has_profile($0
    )
})
}
public func heartwoodIsFollowing(nid: String)throws  -> Bool {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeHeartwoodError.lift) {
    uniffi_rustylib_fn_func_heartwood_is_following(
        FfiConverterString.lower(nid),$0
    )
})
}
public func heartwoodIsSeeding(rid: String)throws  -> Bool {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeHeartwoodError.lift) {
    uniffi_rustylib_fn_func_heartwood_is_seeding(
        FfiConverterString.lower(rid),$0
    )
})
}
public func heartwoodNodeInfo()throws  -> HeartwoodNodeInfo {
    return try  FfiConverterTypeHeartwoodNodeInfo.lift(try rustCallWithError(FfiConverterTypeHeartwoodError.lift) {
    uniffi_rustylib_fn_func_heartwood_node_info($0
    )
})
}
public func heartwoodNodeSessions()throws  -> [HeartwoodSession] {
    return try  FfiConverterSequenceTypeHeartwoodSession.lift(try rustCallWithError(FfiConverterTypeHeartwoodError.lift) {
    uniffi_rustylib_fn_func_heartwood_node_sessions($0
    )
})
}
public func heartwoodNodeStatus()throws  -> HeartwoodNodeStatus {
    return try  FfiConverterTypeHeartwoodNodeStatus.lift(try rustCallWithError(FfiConverterTypeHeartwoodError.lift) {
    uniffi_rustylib_fn_func_heartwood_node_status($0
    )
})
}
public func heartwoodNodesForAlias(alias: String)throws  -> [String] {
    return try  FfiConverterSequenceString.lift(try rustCallWithError(FfiConverterTypeHeartwoodError.lift) {
    uniffi_rustylib_fn_func_heartwood_nodes_for_alias(
        FfiConverterString.lower(alias),$0
    )
})
}
public func heartwoodNotificationCount()throws  -> UInt64 {
    return try  FfiConverterUInt64.lift(try rustCallWithError(FfiConverterTypeHeartwoodError.lift) {
    uniffi_rustylib_fn_func_heartwood_notification_count($0
    )
})
}
public func heartwoodNotificationCountsByRepo()throws  -> [HeartwoodNotificationCount] {
    return try  FfiConverterSequenceTypeHeartwoodNotificationCount.lift(try rustCallWithError(FfiConverterTypeHeartwoodError.lift) {
    uniffi_rustylib_fn_func_heartwood_notification_counts_by_repo($0
    )
})
}
public func heartwoodPaths()throws  -> HeartwoodPaths {
    return try  FfiConverterTypeHeartwoodPaths.lift(try rustCallWithError(FfiConverterTypeHeartwoodError.lift) {
    uniffi_rustylib_fn_func_heartwood_paths($0
    )
})
}
public func heartwoodPing() -> String {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_rustylib_fn_func_heartwood_ping($0
    )
})
}
public func heartwoodRemoveConnectAddress(address: String)throws  {try rustCallWithError(FfiConverterTypeHeartwoodError.lift) {
    uniffi_rustylib_fn_func_heartwood_remove_connect_address(
        FfiConverterString.lower(address),$0
    )
}
}
public func heartwoodRemoveExternalAddress(address: String)throws  {try rustCallWithError(FfiConverterTypeHeartwoodError.lift) {
    uniffi_rustylib_fn_func_heartwood_remove_external_address(
        FfiConverterString.lower(address),$0
    )
}
}
public func heartwoodRemoveListenAddress(address: String)throws  {try rustCallWithError(FfiConverterTypeHeartwoodError.lift) {
    uniffi_rustylib_fn_func_heartwood_remove_listen_address(
        FfiConverterString.lower(address),$0
    )
}
}
public func heartwoodRepository(rid: String)throws  -> HeartwoodRepositoryInfo? {
    return try  FfiConverterOptionTypeHeartwoodRepositoryInfo.lift(try rustCallWithError(FfiConverterTypeHeartwoodError.lift) {
    uniffi_rustylib_fn_func_heartwood_repository(
        FfiConverterString.lower(rid),$0
    )
})
}
public func heartwoodRepositoryBranches(rid: String)throws  -> [HeartwoodRef] {
    return try  FfiConverterSequenceTypeHeartwoodRef.lift(try rustCallWithError(FfiConverterTypeHeartwoodError.lift) {
    uniffi_rustylib_fn_func_heartwood_repository_branches(
        FfiConverterString.lower(rid),$0
    )
})
}
public func heartwoodRepositoryIssueCounts(rid: String)throws  -> HeartwoodIssueCounts? {
    return try  FfiConverterOptionTypeHeartwoodIssueCounts.lift(try rustCallWithError(FfiConverterTypeHeartwoodError.lift) {
    uniffi_rustylib_fn_func_heartwood_repository_issue_counts(
        FfiConverterString.lower(rid),$0
    )
})
}
public func heartwoodRepositoryList()throws  -> [HeartwoodRepositoryInfo] {
    return try  FfiConverterSequenceTypeHeartwoodRepositoryInfo.lift(try rustCallWithError(FfiConverterTypeHeartwoodError.lift) {
    uniffi_rustylib_fn_func_heartwood_repository_list($0
    )
})
}
public func heartwoodRepositoryLog(rid: String, limit: UInt32)throws  -> [HeartwoodCommit] {
    return try  FfiConverterSequenceTypeHeartwoodCommit.lift(try rustCallWithError(FfiConverterTypeHeartwoodError.lift) {
    uniffi_rustylib_fn_func_heartwood_repository_log(
        FfiConverterString.lower(rid),
        FfiConverterUInt32.lower(limit),$0
    )
})
}
public func heartwoodRepositoryPatchCounts(rid: String)throws  -> HeartwoodPatchCounts? {
    return try  FfiConverterOptionTypeHeartwoodPatchCounts.lift(try rustCallWithError(FfiConverterTypeHeartwoodError.lift) {
    uniffi_rustylib_fn_func_heartwood_repository_patch_counts(
        FfiConverterString.lower(rid),$0
    )
})
}
public func heartwoodRepositoryRemotes(rid: String)throws  -> [HeartwoodRemote] {
    return try  FfiConverterSequenceTypeHeartwoodRemote.lift(try rustCallWithError(FfiConverterTypeHeartwoodError.lift) {
    uniffi_rustylib_fn_func_heartwood_repository_remotes(
        FfiConverterString.lower(rid),$0
    )
})
}
public func heartwoodRepositorySeedCount(rid: String)throws  -> UInt64 {
    return try  FfiConverterUInt64.lift(try rustCallWithError(FfiConverterTypeHeartwoodError.lift) {
    uniffi_rustylib_fn_func_heartwood_repository_seed_count(
        FfiConverterString.lower(rid),$0
    )
})
}
public func heartwoodRoutingSummary()throws  -> HeartwoodRoutingSummary {
    return try  FfiConverterTypeHeartwoodRoutingSummary.lift(try rustCallWithError(FfiConverterTypeHeartwoodError.lift) {
    uniffi_rustylib_fn_func_heartwood_routing_summary($0
    )
})
}
public func heartwoodSeedPolicies()throws  -> [HeartwoodSeedPolicy] {
    return try  FfiConverterSequenceTypeHeartwoodSeedPolicy.lift(try rustCallWithError(FfiConverterTypeHeartwoodError.lift) {
    uniffi_rustylib_fn_func_heartwood_seed_policies($0
    )
})
}
public func heartwoodSetAlias(newAlias: String)throws  {try rustCallWithError(FfiConverterTypeHeartwoodError.lift) {
    uniffi_rustylib_fn_func_heartwood_set_alias(
        FfiConverterString.lower(newAlias),$0
    )
}
}
public func heartwoodSetNetwork(mode: String)throws  {try rustCallWithError(FfiConverterTypeHeartwoodError.lift) {
    uniffi_rustylib_fn_func_heartwood_set_network(
        FfiConverterString.lower(mode),$0
    )
}
}
public func heartwoodSetRelay(mode: String)throws  {try rustCallWithError(FfiConverterTypeHeartwoodError.lift) {
    uniffi_rustylib_fn_func_heartwood_set_relay(
        FfiConverterString.lower(mode),$0
    )
}
}
public func heartwoodVersion() -> String {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_rustylib_fn_func_heartwood_version($0
    )
})
}
public func normalizeAlias(input: String) -> String? {
    return try!  FfiConverterOptionString.lift(try! rustCall() {
    uniffi_rustylib_fn_func_normalize_alias(
        FfiConverterString.lower(input),$0
    )
})
}
public func normalizeNodeId(input: String) -> String? {
    return try!  FfiConverterOptionString.lift(try! rustCall() {
    uniffi_rustylib_fn_func_normalize_node_id(
        FfiConverterString.lower(input),$0
    )
})
}
public func normalizeRepoId(input: String) -> String? {
    return try!  FfiConverterOptionString.lift(try! rustCall() {
    uniffi_rustylib_fn_func_normalize_repo_id(
        FfiConverterString.lower(input),$0
    )
})
}
public func rustAdd(a: UInt32, b: UInt32) -> UInt32 {
    return try!  FfiConverterUInt32.lift(try! rustCall() {
    uniffi_rustylib_fn_func_rust_add(
        FfiConverterUInt32.lower(a),
        FfiConverterUInt32.lower(b),$0
    )
})
}
public func rustHello() -> String {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_rustylib_fn_func_rust_hello($0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private var initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_rustylib_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_rustylib_checksum_func_heartwood_add_connect_address() != 49131) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_heartwood_add_external_address() != 40825) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_heartwood_add_listen_address() != 22113) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_heartwood_alias_for_node() != 51339) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_heartwood_answer() != 4271) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_heartwood_commit() != 16525) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_heartwood_follow_policies() != 40008) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_heartwood_has_profile() != 62768) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_heartwood_is_following() != 58358) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_heartwood_is_seeding() != 59320) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_heartwood_node_info() != 33573) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_heartwood_node_sessions() != 57868) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_heartwood_node_status() != 6548) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_heartwood_nodes_for_alias() != 52837) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_heartwood_notification_count() != 38100) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_heartwood_notification_counts_by_repo() != 47640) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_heartwood_paths() != 35544) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_heartwood_ping() != 43370) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_heartwood_remove_connect_address() != 16985) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_heartwood_remove_external_address() != 28540) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_heartwood_remove_listen_address() != 57918) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_heartwood_repository() != 58935) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_heartwood_repository_branches() != 60987) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_heartwood_repository_issue_counts() != 42917) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_heartwood_repository_list() != 26992) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_heartwood_repository_log() != 30337) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_heartwood_repository_patch_counts() != 22642) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_heartwood_repository_remotes() != 41429) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_heartwood_repository_seed_count() != 49650) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_heartwood_routing_summary() != 40651) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_heartwood_seed_policies() != 11249) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_heartwood_set_alias() != 50113) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_heartwood_set_network() != 47236) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_heartwood_set_relay() != 6716) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_heartwood_version() != 58832) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_normalize_alias() != 18130) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_normalize_node_id() != 60672) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_normalize_repo_id() != 35590) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_rust_add() != 47653) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_rustylib_checksum_func_rust_hello() != 11814) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:disable all